// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: employee.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmpRequest) Reset() {
	*x = EmpRequest{}
	mi := &file_employee_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmpRequest) ProtoMessage() {}

func (x *EmpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_employee_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmpRequest.ProtoReflect.Descriptor instead.
func (*EmpRequest) Descriptor() ([]byte, []int) {
	return file_employee_proto_rawDescGZIP(), []int{0}
}

func (x *EmpRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type EmpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Dept          string                 `protobuf:"bytes,2,opt,name=dept,proto3" json:"dept,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmpResponse) Reset() {
	*x = EmpResponse{}
	mi := &file_employee_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmpResponse) ProtoMessage() {}

func (x *EmpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_employee_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmpResponse.ProtoReflect.Descriptor instead.
func (*EmpResponse) Descriptor() ([]byte, []int) {
	return file_employee_proto_rawDescGZIP(), []int{1}
}

func (x *EmpResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EmpResponse) GetDept() string {
	if x != nil {
		return x.Dept
	}
	return ""
}

var File_employee_proto protoreflect.FileDescriptor

const file_employee_proto_rawDesc = "" +
	"\n" +
	"\x0eemployee.proto\x12\bemployee\"\x1c\n" +
	"\n" +
	"EmpRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"5\n" +
	"\vEmpResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04dept\x18\x02 \x01(\tR\x04dept2\x87\x01\n" +
	"\bEmployee\x12<\n" +
	"\rGetEmpDetails\x12\x14.employee.EmpRequest\x1a\x15.employee.EmpResponse\x12=\n" +
	"\x0ePostEmpDetails\x12\x15.employee.EmpResponse\x1a\x14.employee.EmpRequestB\x12Z\x10grpc/proto;protob\x06proto3"

var (
	file_employee_proto_rawDescOnce sync.Once
	file_employee_proto_rawDescData []byte
)

func file_employee_proto_rawDescGZIP() []byte {
	file_employee_proto_rawDescOnce.Do(func() {
		file_employee_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_employee_proto_rawDesc), len(file_employee_proto_rawDesc)))
	})
	return file_employee_proto_rawDescData
}

var file_employee_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_employee_proto_goTypes = []any{
	(*EmpRequest)(nil),  // 0: employee.EmpRequest
	(*EmpResponse)(nil), // 1: employee.EmpResponse
}
var file_employee_proto_depIdxs = []int32{
	0, // 0: employee.Employee.GetEmpDetails:input_type -> employee.EmpRequest
	1, // 1: employee.Employee.PostEmpDetails:input_type -> employee.EmpResponse
	1, // 2: employee.Employee.GetEmpDetails:output_type -> employee.EmpResponse
	0, // 3: employee.Employee.PostEmpDetails:output_type -> employee.EmpRequest
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_employee_proto_init() }
func file_employee_proto_init() {
	if File_employee_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_employee_proto_rawDesc), len(file_employee_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_employee_proto_goTypes,
		DependencyIndexes: file_employee_proto_depIdxs,
		MessageInfos:      file_employee_proto_msgTypes,
	}.Build()
	File_employee_proto = out.File
	file_employee_proto_goTypes = nil
	file_employee_proto_depIdxs = nil
}
