// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: employee.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Employee_GetEmpDetails_FullMethodName  = "/employee.Employee/GetEmpDetails"
	Employee_PostEmpDetails_FullMethodName = "/employee.Employee/PostEmpDetails"
)

// EmployeeClient is the client API for Employee service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EmployeeClient interface {
	GetEmpDetails(ctx context.Context, in *EmpRequest, opts ...grpc.CallOption) (*EmpResponse, error)
	PostEmpDetails(ctx context.Context, in *EmpResponse, opts ...grpc.CallOption) (*EmpRequest, error)
}

type employeeClient struct {
	cc grpc.ClientConnInterface
}

func NewEmployeeClient(cc grpc.ClientConnInterface) EmployeeClient {
	return &employeeClient{cc}
}

func (c *employeeClient) GetEmpDetails(ctx context.Context, in *EmpRequest, opts ...grpc.CallOption) (*EmpResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmpResponse)
	err := c.cc.Invoke(ctx, Employee_GetEmpDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *employeeClient) PostEmpDetails(ctx context.Context, in *EmpResponse, opts ...grpc.CallOption) (*EmpRequest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmpRequest)
	err := c.cc.Invoke(ctx, Employee_PostEmpDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmployeeServer is the server API for Employee service.
// All implementations must embed UnimplementedEmployeeServer
// for forward compatibility.
type EmployeeServer interface {
	GetEmpDetails(context.Context, *EmpRequest) (*EmpResponse, error)
	PostEmpDetails(context.Context, *EmpResponse) (*EmpRequest, error)
	mustEmbedUnimplementedEmployeeServer()
}

// UnimplementedEmployeeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEmployeeServer struct{}

func (UnimplementedEmployeeServer) GetEmpDetails(context.Context, *EmpRequest) (*EmpResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEmpDetails not implemented")
}
func (UnimplementedEmployeeServer) PostEmpDetails(context.Context, *EmpResponse) (*EmpRequest, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostEmpDetails not implemented")
}
func (UnimplementedEmployeeServer) mustEmbedUnimplementedEmployeeServer() {}
func (UnimplementedEmployeeServer) testEmbeddedByValue()                  {}

// UnsafeEmployeeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EmployeeServer will
// result in compilation errors.
type UnsafeEmployeeServer interface {
	mustEmbedUnimplementedEmployeeServer()
}

func RegisterEmployeeServer(s grpc.ServiceRegistrar, srv EmployeeServer) {
	// If the following call pancis, it indicates UnimplementedEmployeeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Employee_ServiceDesc, srv)
}

func _Employee_GetEmpDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeServer).GetEmpDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Employee_GetEmpDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeServer).GetEmpDetails(ctx, req.(*EmpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Employee_PostEmpDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmpResponse)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeServer).PostEmpDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Employee_PostEmpDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeServer).PostEmpDetails(ctx, req.(*EmpResponse))
	}
	return interceptor(ctx, in, info, handler)
}

// Employee_ServiceDesc is the grpc.ServiceDesc for Employee service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Employee_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "employee.Employee",
	HandlerType: (*EmployeeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetEmpDetails",
			Handler:    _Employee_GetEmpDetails_Handler,
		},
		{
			MethodName: "PostEmpDetails",
			Handler:    _Employee_PostEmpDetails_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "employee.proto",
}
